name: Release
run-name: Release ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

jobs:
  setup:
    name: Setup
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    outputs:
      release_version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check branch
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================="
            echo "[!] Can only release from the 'main' branch"
            echo "==================================="
            exit 1
          fi

      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get version
        id: version
        run: |
          VERSION=$(sed -nE 's/^VERSION\s+\?=\s+([^\s]+)/\1/p' Makefile)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: setup
    env:
      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
    permissions:
      contents: write

    steps:
      - name: Create release
        if: ${{ inputs.release_type != 'Dry Run' }}
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          commit: ${{ github.sha }}
          tag: v${{ env._PKG_VERSION }}
          name: v${{ env._PKG_VERSION }}
          body: "<insert release notes here>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  release-ghcr:
    name: Push Release to GitHub Container Registry
    runs-on: ubuntu-24.04
    needs:
      - setup
      - release
    env:
      _RELEASE_TAG: ${{ needs.setup.outputs.release_version }}
      _IMAGE_NAME: ghcr.io/bitwarden/sm-operator
    permissions:
      packages: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dry Run - Pull, tag, and push release
        if: ${{ inputs.release_type == 'Dry Run' }}
        run: |
          docker pull ${{ env._IMAGE_NAME }}:dev
          docker tag ${{ env._IMAGE_NAME }}:dev ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }}

      - name: Pull, tag, and push release
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          docker pull ${{ env._IMAGE_NAME }}:dev
          docker tag ${{ env._IMAGE_NAME }}:dev ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }}
          docker push ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }}

      - name: Log out of Docker
        run: docker logout ghcr.io
