name: Release
run-name: Release ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

jobs:
  setup:
    name: Setup
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    outputs:
      release_version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check branch
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================="
            echo "[!] Can only release from the 'main' branch"
            echo "==================================="
            exit 1
          fi

      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Get version
        id: version
        run: |
          VERSION=$(sed -nE 's/^VERSION\s+\?=\s+([^\s]+)/\1/p' Makefile)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: setup
    env:
      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
    permissions:
      contents: write

    steps:
      - name: Create release
        if: ${{ inputs.release_type != 'Dry Run' }}
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          commit: ${{ github.sha }}
          tag: v${{ env._PKG_VERSION }}
          name: v${{ env._PKG_VERSION }}
          body: "<insert release notes here>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  release-ghcr:
    name: Push Release to GitHub Container Registry
    runs-on: ubuntu-24.04
    needs:
      - setup
      - release
    env:
      _MAIN_TAG: dev
      _RELEASE_TAG: ${{ needs.setup.outputs.release_version }}
      _IMAGE_NAME: ghcr.io/bitwarden/sm-operator
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Push release image
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          skopeo copy --all \
            docker://$_IMAGE_NAME:$_MAIN_TAG \
            docker://$_IMAGE_NAME:$_RELEASE_TAG

      - name: Sign release image with Cosign
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          DIGEST=$(skopeo inspect --raw docker://$_IMAGE_NAME:$_RELEASE_TAG | sha256sum | awk '{printf "sha256:%s", $1}')
          cosign sign --yes "$_IMAGE_NAME:$_RELEASE_TAG@$DIGEST"

      - name: Log out of Docker
        run: docker logout ghcr.io
